stages:
  prepare:
    cmd: python data_prep.py
    deps:
      - data_prep.py
      - dataset.csv
    params:
      - prepare.age_threshold
    outs:
      - outs/dataset_cleaned.csv


  process:
    cmd: python data_process.py
    deps:
      - data_process.py
      - outs/dataset_cleaned.csv
    params:
      - process.test_size
      - process.seed
    outs:
      - outs/processed_X_train.csv
      - outs/processed_X_test.csv
      - outs/processed_y_train.csv
      - outs/processed_y_test.csv

  train:
    cmd: python data_train.py
    deps:
      - data_train.py
      - outs/processed_X_train.csv
      - outs/processed_X_test.csv
      - outs/processed_y_train.csv
      - outs/processed_y_test.csv
    params:
        - train.n_estimators
        - train.max_depth
    outs:
      - conf_matrix.png

    metrics:
      - metrics.json:
          cache: False

plots:
  - ./conf_matrix.png
  - ./roc_curve.png
  - ROC:
      x: fpr
      y:
        roc_data.csv: "tpr\r"



  # evaluate:
  