name: churn-imbalanced-dataset
on: [push]
permissions: write-all
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: iterative/setup-cml@v1


      - name: Prepare Environment
        run: |
          # Your ML workflow goes here
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Generate Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc repro
          git fetch --prune

          # Get the report
          echo "## Metrics" > report.md
          dvc metrics diff main >> report.md

          echo "## Confusion Matrix" >> report.md
          echo "![](./conf_matrix.png)" >> report.md
          cml comment create report.md